### ISSUE TITLE
rnn example - error

### ISSUE THREAD

**Issue by andrewczgithub** [philipperemy/n-beats#17]
Hi @philipperemy !

I hope your well.

I am getting an error on the rnn example

```python 
==================================================================================================
Total params: 4,164,880
Trainable params: 4,164,880
Non-trainable params: 0
__________________________________________________________________________________________________
compile_model()
fit()
Traceback (most recent call last):
  File "examples/rnn_example.py", line 126, in <module>
    callbacks=[EvaluateModelCallback()])
  File "/home/andrewcz/tutorial-env1/lib/python3.7/site-packages/nbeats_keras-1.3.0-py3.7.egg/nbeats_keras/model.py", line 163, in wrapper
  File "/home/andrewcz/tutorial-env1/lib/python3.7/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/home/andrewcz/tutorial-env1/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/home/andrewcz/tutorial-env1/lib/python3.7/site-packages/keras/engine/training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_variable to have 3 dimensions, but got array with shape (299980, 20)

```

**Comment by philipperemy** [comment]
Hey @andrewczgithub should be fixed with https://github.com/philipperemy/n-beats/pull/18

**Comment by andrewczgithub** [comment]
thank you :)
